export const DOMAIN_USER_REPOSITORY = Symbol('DOMAIN_USER_REPOSITORY');
export const DOMAIN_TASK_REPOSITORY = Symbol('DOMAIN_TASK_REPOSITORY');
export const DOMAIN_GROUP_REPOSITORY = Symbol('DOMAIN_GROUP_REPOSITORY');
export const DOMAIN_SUBTASK_REPOSITORY = Symbol('DOMAIN_SUBTASK_REPOSITORY');
export const DOMAIN_GROUPMEMBER_REPOSITORY = Symbol(
  'DOMAIN_GROUPMEMBER_REPOSITORY'
);
export const DOMAIN_COMMENT_REPOSITORY = Symbol('DOMAIN_COMMENT_REPOSITORY');
